#!/bin/bash
#
# Update de ConTeXt versie in deze map naar de laatste versie
#
# Tim Steenvoorden, MMXIIV

cd /vol/impuls/context

rsync -tv rsync://contextgarden.net/minimals/setup/first-setup.sh .
./first-setup.sh
rm first-setup.sh

cd -
